# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py_file_client.ui'
#
# Created: Tue Jan 14 15:46:46 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(909, 631)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/7fe8770a7445746def3c307e53a17992.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEditIP = QtGui.QLineEdit(self.centralwidget)
        self.lineEditIP.setObjectName(_fromUtf8("lineEditIP"))
        self.horizontalLayout.addWidget(self.lineEditIP)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditPort = QtGui.QLineEdit(self.centralwidget)
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.horizontalLayout.addWidget(self.lineEditPort)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEditDirectoryClient = QtGui.QLineEdit(self.centralwidget)
        self.lineEditDirectoryClient.setObjectName(_fromUtf8("lineEditDirectoryClient"))
        self.horizontalLayout.addWidget(self.lineEditDirectoryClient)
        self.pushButtonDirClient = QtGui.QPushButton(self.centralwidget)
        self.pushButtonDirClient.setWhatsThis(_fromUtf8(""))
        self.pushButtonDirClient.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/folder.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDirClient.setIcon(icon1)
        self.pushButtonDirClient.setObjectName(_fromUtf8("pushButtonDirClient"))
        self.horizontalLayout.addWidget(self.pushButtonDirClient)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEditDirectory = QtGui.QLineEdit(self.centralwidget)
        self.lineEditDirectory.setObjectName(_fromUtf8("lineEditDirectory"))
        self.horizontalLayout_2.addWidget(self.lineEditDirectory)
        self.checkBoxHidden = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxHidden.setObjectName(_fromUtf8("checkBoxHidden"))
        self.horizontalLayout_2.addWidget(self.checkBoxHidden)
        self.pushButtonUp = QtGui.QPushButton(self.centralwidget)
        self.pushButtonUp.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/go-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUp.setIcon(icon2)
        self.pushButtonUp.setObjectName(_fromUtf8("pushButtonUp"))
        self.horizontalLayout_2.addWidget(self.pushButtonUp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonGet = QtGui.QPushButton(self.centralwidget)
        self.pushButtonGet.setWhatsThis(_fromUtf8(""))
        self.pushButtonGet.setObjectName(_fromUtf8("pushButtonGet"))
        self.horizontalLayout_3.addWidget(self.pushButtonGet)
        self.pushButtonStop = QtGui.QPushButton(self.centralwidget)
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.horizontalLayout_3.addWidget(self.pushButtonStop)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonClear = QtGui.QPushButton(self.centralwidget)
        self.pushButtonClear.setWhatsThis(_fromUtf8(""))
        self.pushButtonClear.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/edit-delete.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClear.setIcon(icon3)
        self.pushButtonClear.setObjectName(_fromUtf8("pushButtonClear"))
        self.horizontalLayout_4.addWidget(self.pushButtonClear)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_2.addWidget(self.listWidget)
        spacerItem3 = QtGui.QSpacerItem(40, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyFileClient", None))
        self.label.setText(_translate("MainWindow", "Server IP address:", None))
        self.label_2.setText(_translate("MainWindow", "Port:", None))
        self.label_4.setText(_translate("MainWindow", "Directory on Client:", None))
        self.pushButtonDirClient.setToolTip(_translate("MainWindow", "Select the directory on the client", None))
        self.label_3.setText(_translate("MainWindow", "Directory on Server:", None))
        self.checkBoxHidden.setText(_translate("MainWindow", "Show hidden files", None))
        self.pushButtonUp.setToolTip(_translate("MainWindow", "Move up one directory level", None))
        self.pushButtonGet.setToolTip(_translate("MainWindow", "Get the files from server and put them to the client directory, Ctrl+G", None))
        self.pushButtonGet.setText(_translate("MainWindow", "Get file(s)", None))
        self.pushButtonGet.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop Server", None))
        self.pushButtonClear.setToolTip(_translate("MainWindow", "Clear the protocol, Ctrl+L", None))
        self.pushButtonClear.setShortcut(_translate("MainWindow", "Ctrl+L", None))

